### PR TITLE
WIP test: run tests in browser

### PR DESCRIPTION
**Pull request by marten-de-vries**
Fixes issue #10.

At least, as soon as the PR works. I get some buffertools error that's apparently quite specific to my system, so I can't test myself currently. Trying travis now, although if that doesn't work I guess I should find another system.

### CODE REVIEW

**Comment by gr2m** [comment]
I’ve seen that there is a problem with saucelabs credentials, looking into it

**Comment by gr2m** [comment]
Can you create a [.zuulrc](https://github.com/defunctzombie/zuul/wiki/Zuulrc) file with 

```
sauce_username: $(SAUCE_USERNAME)
sauce_key: $(SAUCE_ACCESS_KEY)
```

before tests are run in `.travis.yml`? I couldn’t find out if `zuul` accepts configuration via environment variables or cli arguments

**Comment by marten-de-vries** [comment]
Are you sure it's not just a Travis safety feature? If what you suggest would work, there technically nothing to prevent me from modifying .travis.yml to echo the variable values into the build log.

Anyway, I tried to get this to run in a Docker image to actually test it locally, but that fails too. That makes it less likely it would pass Travis even after the credentials thing is solved:

Dockerfile:

``` Dockerfile
FROM node:0.12

RUN git clone https://github.com/marten-de-vries/couchdb-calculate-session-id.git && \
  cd couchdb-calculate-session-id && \
  git checkout browser-testing && \
  npm install

WORKDIR "/couchdb-calculate-session-id"
EXPOSE 8080
CMD ["npm", "run", "test:browser:local"]
```

docker-compose.yml:

``` yml
test:
  build: .
  ports:
    - "8080:8080"
```

terminal:

``` bash
marten@procyon:~/Bureaublad/temp$ docker-compose build && docker-compose up
Building test
Step 1 : FROM node:0.12
 ---> e02d3f07356a
Step 2 : RUN git clone https://github.com/marten-de-vries/couchdb-calculate-session-id.git &&   cd couchdb-calculate-session-id &&   git checkout browser-testing &&   npm install
 ---> Using cache
 ---> 44fae8fbc158
Step 3 : WORKDIR "/couchdb-calculate-session-id"
 ---> Running in ffddcfc9ed36
 ---> 7e4e001e63f5
Removing intermediate container ffddcfc9ed36
Step 4 : EXPOSE 8080
 ---> Running in 2f941673636d
 ---> 778b2d8bbd45
Removing intermediate container 2f941673636d
Step 5 : CMD npm run test:browser:local
 ---> Running in 1697c3dfc1f8
 ---> e1a72d482324
Removing intermediate container 1697c3dfc1f8
Successfully built e1a72d482324
Recreating temp_test_1
Attaching to temp_test_1
test_1 | 
test_1 | > couchdb-calculate-session-id@ test:browser:local /couchdb-calculate-session-id
test_1 | > zuul --local 8080 -- tests
test_1 | 

test_1 | open the following url in a browser:
test_1 | http://localhost:8080/__zuul
test_1 | Error: Cannot find module 'buffertools' from '/couchdb-calculate-session-id/node_modules/tap/node_modules/only-shallow'
test_1 |     at /couchdb-calculate-session-id/node_modules/zuul/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
test_1 |     at process (/couchdb-calculate-session-id/node_modules/zuul/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
test_1 |     at ondir (/couchdb-calculate-session-id/node_modules/zuul/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
test_1 |     at load (/couchdb-calculate-session-id/node_modules/zuul/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
test_1 |     at onex (/couchdb-calculate-session-id/node_modules/zuul/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
test_1 |     at /couchdb-calculate-session-id/node_modules/zuul/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
test_1 |     at FSReqWrap.oncomplete (fs.js:95:15)
test_1 | Error: Cannot find module 'buffertools' from '/couchdb-calculate-session-id/node_modules/tap/node_modules/tmatch'
test_1 |     at /couchdb-calculate-session-id/node_modules/zuul/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
test_1 |     at process (/couchdb-calculate-session-id/node_modules/zuul/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
test_1 |     at ondir (/couchdb-calculate-session-id/node_modules/zuul/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
test_1 |     at load (/couchdb-calculate-session-id/node_modules/zuul/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
test_1 |     at onex (/couchdb-calculate-session-id/node_modules/zuul/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
test_1 |     at /couchdb-calculate-session-id/node_modules/zuul/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
test_1 |     at FSReqWrap.oncomplete (fs.js:95:15)
test_1 | Error: Cannot find module 'buffertools' from '/couchdb-calculate-session-id/node_modules/tap/node_modules/deeper'
test_1 |     at /couchdb-calculate-session-id/node_modules/zuul/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
test_1 |     at process (/couchdb-calculate-session-id/node_modules/zuul/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
test_1 |     at ondir (/couchdb-calculate-session-id/node_modules/zuul/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
test_1 |     at load (/couchdb-calculate-session-id/node_modules/zuul/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
test_1 |     at onex (/couchdb-calculate-session-id/node_modules/zuul/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
test_1 |     at /couchdb-calculate-session-id/node_modules/zuul/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
test_1 |     at FSReqWrap.oncomplete (fs.js:95:15)
^CGracefully stopping... (press Ctrl+C again to force)
Stopping temp_test_1 ... 
Killing temp_test_1 ... done
```

**Comment by gr2m** [comment]
thanks Marten, I’m looking into it

**Comment by gr2m** [comment]
looks like you are right: https://github.com/defunctzombie/zuul/issues/86, but then I don’t get why this works: https://travis-ci.org/hoodiehq/pouchdb-hoodie-api/jobs/92519664

**Comment by gr2m** [comment]
Ah okay, because yours is a fork. Works if I push a branch: https://travis-ci.org/hoodiehq/couchdb-calculate-session-id/jobs/99084461

Learned something new :) Also making you a contributor now

**Comment by gr2m** [comment]
I get the same `Error: Cannot find module 'buffertools' from` when running `npm run test:browser:local` ... no idea where this comes from, haven’t seen that before

**Comment by gr2m** [comment]
Ah wait I think it’s `tap`, as we test in browsers now, we need to use `tape`, let me try that

**Comment by gr2m** [comment]
got it working in https://github.com/hoodiehq/couchdb-calculate-session-id/pull/12. Do you want to squash the commits into one `test: ...` commit? I can do it, too, but I don’t want to steal your work :)

**Comment by marten-de-vries** [comment]
Sure.

**Pull request closed without merging**
