### PR TITLE
Invalid Session ID calculation

### PR DESCRIPTION
**Pull request by gr2m**
I took these from a real CouchDB:
- session id
- username
- salt
- CouchDB secret
- timestamp

and pasted it into an extra test – it fails :(

This blocks us from releasing new Hoodie – please help!

### CODE REVIEW

**Comment by gr2m** [comment]
@christophwitzko I don’t know what happened. I tested this once by copy & pasting the calculated session ID into my CouchDB cookie – and it worked. Now it doesn’t anymore and I don’t understand why. Could you have a look? This is blocking a Hoodie pre-release right now, it’s the last blocking bit

**Comment by gr2m** [comment]
To be more precise, the original test from @janl’s case discussed at https://gist.github.com/janl/4583f5eb4c0d8216cc5f passes. But with my CouchDB (1.6.1) it does not. Note that the salt in my CouchDB is longer then the one from Jan’s test case

**Comment by gr2m** [comment]
Looks like CouchDB 1.5 has the shorter salt like in Jan’s example. I’ve added another test for CouchDB 1.5, but it also fails.

Oh maaaaan, so close :(

**Comment by kxepal** [comment]
@gr2m you confuse order of secret with usersalt concatenation:

```
%% https://github.com/apache/couchdb-couch/blob/master/src/couch_httpd_auth.erl#L317
Cookie = cookie_auth_cookie(Req, ?b2l(UserName), <<Secret/binary, UserSalt/binary>>, CurrentTime),
```

You did:

```
var hmac = crypto.createHmac('sha1', usersalt + serversecret).update(sessionData);
```

**Comment by gr2m** [comment]
:facepalm: Thanks so much @kxepal, that was it. THANKS SO MUCH!!!

**Comment by marten-de-vries** [comment]
Nice!

**Comment by kxepal** [comment]
@gr2m you're welcome (: Have a good holidays!

**Pull request merged**
