### PR TITLE
browser testing

### PR DESCRIPTION
**Pull request by gr2m**

### CODE REVIEW

**Comment by marten-de-vries** [comment]
Follow up for #11.

**Comment by marten-de-vries** [comment]
I changed one thing before squashing: you removed the 'hmac-browser' file from package.json's browser section, so I put that back.

**Comment by gr2m** [comment]
ooops sorry! Good catch, I did that for debugging

**Comment by marten-de-vries** [comment]
Ah, thought it would be something like that. Wanted to check though.

**Pull request merged**
